paths: 
  /status/:
    get: 
      summary: Retrieve server status
      x-fern-ignore: true
  /pdf/docx/:
    post: 
      summary: Convert a DOC or DOCX to PDF 
      x-fern-sdk-method-name: convert_docx
      x-fern-ignore: true
  /pdf/generate/:
    post: 
      summary: Generate a PDF
      x-fern-sdk-method-name: generate
  /pdf/merge/:
    post: 
      summary: Merge PDFs
      x-fern-sdk-method-name: merge